
print('Szia!')
vezetéknév = input('Mi a vezeték neved? ')
keresztnév = input('Mi a kereszt neved? ')
szuletesi_ev = input('Mi a születési éved? ')
csillagjegy = input('Mi a csillagjegyed? ')
print( )
print('A te neved ', vezetéknév, keresztnév,'.')
print('Születési időd: ',szuletesi_ev)
print('Csillagjegyed: ', csillagjegy)